config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope :api, defaults: {format: :json} do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :jobs, except: [:new, :edit, :show]
    resources :messages, except: [:new, :edit, :update, :show]
    resources :projects, except: [:new, :edit, :show]
    resources :photos, except: [:new, :edit, :show]
    resources :resume, except: [:new, :edit, :index, :show]
    match 'resume', to: 'resume#show', via: :get
  end

  resources :jobs, except: [:create, :update]
  resources :projects, except: [:create, :update]
  resources :photos, except: [:show, :create, :update]
  resources :messages, except: [:edit, :create, :update]

  match 'modeling', to: 'photos#index', via: :get
  match 'portfolio', to: 'pages#portfolio', via: :get
  match 'contact', to: 'messages#new', via: :get
  match 'about', to: 'pages#about', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'resume', to: 'resume#show', via: :get

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  has_many :schools, dependent: :destroy
  accepts_nested_attributes_for :schools
  validate :only_one, on: :create
  #validates :header, :link, :address, :phone, :email, :position, :qualifications, :skills, presence: true

  def only_one
    if Resume.all.length > 0
      errors.add(:Resume, "cannot create more than one entry of this data model")
    end
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
  end
  
  def show
    @jobs = Job.last(3)
    @resume = Resume.first
  end

  def new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      render json: @resume, status: :created
    else
      render json: @resume.errors, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @resume = Resume.first
    if @resume.update(resume_params)
      render json: @resume.attributes.merge(schools: @resume.schools)
    else
      render json: @resume.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @resume = Resume.first
    @school = @resume.schools.find(params[:id])
    if @school.destroy!
      render json: @resume.attributes.merge(schools: @resume.schools)
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:header, :link, :address, :phone, :email, :position, :qualifications, :skills, schools_attributes: [:resume_id, :id, :title, :years, :description])
  end

end

app/views/resume/index.html.erb
<% provide(:title, 'Resume') %>


<!-- cache infrequently changing data to expire based on new model data -->
<div class="resume">
  <div id="resume-header">
    <h2>Ian (Drakken or Adela) Coutu</h2>
    <%= link_to "www.saerdesigns.com", root_path %>
    <address>
      26180 SW CANYON CREEK RD<br>
      APT 104<br>
      WILSONVILLE, OR<br>
      97070
    </address>
    <ul class="nav pull-left">
      678-439-8431
    </ul>
    <ul class="nav pull-right">
      <%= mail_to "shadowdrakkeen@gmail.com", "shadowdrakkeen@gmail.com" %>
    </ul><br>
    <hr class="thick"><hr class="thin">
  </div>
  <div id="resume-body">
    <div id="position">
      <h2>Position desired</h2>
      Ruby on Rails developer
    </div>
    <div id="qualifications">
      <h2>Qualifications</h2>
      6+ years experience with web technologies<br>
      Solid organizational and planning skills<br>
      Knowledge of SEO tactics and practices<br>
      Experience with UI & design<br>
      Knowledge of MVC implementations<br>
    </div>
    <div id="skills">
      <h2>Skills</h2>
      Ruby on Rails, Heroku, Git, AJAX, jQuery, Javascript, CSS3, HTML5, SQL deployment, UNIX, Bootstrap, Ruby, PHP, MySQL, LESS CSS, SASS, Angular JS, PostgreSQL, WordPress, Windows, MacOS, Linux, LivePerson Administration, Windows Phone OS, Customer Service
    </div>
    <div id="history">
      <h2>Work History</h2>
      <% @jobs.each do |job| %>
      <div>
        <a href="<%= job_path(job) %>"><h3><%= job.title %></h3></a><br>
        <%= job.company %><br>
        <% if !job.years.empty? %><%= job.years %><br><% end %>
        <%= job.description %><br>
        <% if !job.references.first.reference.first.empty? %>
          <br>
          <b>Professional References</b>
          <% job.references.order(:id).each do |person| %>
            <li><%= person.reference %></li>
          <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
    <div id="education">
    </div>
  </div>
</div>