config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope :api, defaults: {format: :json} do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :jobs, except: [:new, :edit, :show]
    resources :messages, except: [:new, :edit, :update, :show]
    resources :projects, except: [:new, :edit, :show]
    resources :photos, except: [:new, :edit, :show]
    resources :resume, except: [:new, :edit, :index, :show]
    match 'resume', to: 'resume#show', via: :get
  end

  resources :jobs, except: [:create, :update]
  resources :projects, except: [:create, :update]
  resources :photos, except: [:show, :create, :update]
  resources :messages, except: [:edit, :create, :update]

  match 'modeling', to: 'photos#index', via: :get
  match 'portfolio', to: 'pages#portfolio', via: :get
  match 'contact', to: 'messages#new', via: :get
  match 'about', to: 'pages#about', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'resume', to: 'resume#show', via: :get

end

app/models/project.rb
class Project < ActiveRecord::Base
  before_save :falsify_all_primary

  validates :title, :link, :description, presence: true, uniqueness: true, length: {minimum: 6}

  has_attached_file :image, 
  styles: { small: "300x300>", medium: "400x400>", large: "500x500>" }, 
  default_url: "/images/paperclip/:style/missing.png"

  validates_attachment :image, presence: true, 
  content_type: { content_type: /\Aimage\/.*\Z/ }, 
  size: { less_than: 5.megabytes }
  
  private
  def falsify_all_primary
    if self.is_primary == true
      self.class.where('id != ?', self.id).update_all(is_primary: "false"); 
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  
  def index
    @projects = Project.all
  end
  
  def show
  end
  
  def new
  end
  
  def create
    @project = Project.new(project_params)
    if @project.save
      render json: @project.attributes.merge(
        image_original: @project.image.url(:original),
        image_large: @project.image.url(:large),
        image_medium: @project.image.url(:medium),
        image_small: @project.image.url(:small)
        ), status: :created
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end
  
  def edit
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      render json: @project.attributes.merge(
        image_original: @project.image.url(:original),
        image_large: @project.image.url(:large),
        image_medium: @project.image.url(:medium),
        image_small: @project.image.url(:small)
        )
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.image = nil
    if @project.destroy!
      render nothing: true
    end
  end
  
  private
  
    def project_params
      params.require(:project).permit(:title, :description, :link, :image, :is_primary)
    end

end

app/views/projects/_display.html.erb
<div class="<%= col_size %> portfolio">
  <ul class="center">    
    <% if current_page?(action: 'index') %><h2><%= project.title %></h2>
    <li><%= link_to image_tag(project.image.url(size), class: img_type), link, class: "img-thumbnail img-darken" %></li>
    <% else %>
    <li><%= link_to image_tag(project.image.url(size), class: img_type), link, class: img_type + " img-darken" %></li>
    <li><%= link_to 'Visit the website', project.link %></li>
    <li><b>Description</b></li><li><%= word_wrap(description, line_width: 50) %></li>
    <li><%= link_to "View details >>", project, class: "btn btn-default" if current_page?(action: 'index') %></li>
    <% if signed_in? && current_page?(project) %>
    <li>
      <%= link_to 'Edit project', edit_project_path(project) %> | 
      <%= link_to 'Delete project', project, method: :delete,  data:{confirm: "Are you sure?"} %>
    </li>
    <% end %>
    <% end %>
  </ul>
</div>